# Contents
1. Basics of channels
    - Definition
    - Unitary channels
    - Convex combinations
    - Examples of qubit channels
2. Channel Representations
    - Stinespring
    - Kraus
    - Choi
3. Equivalence of representations

# What are Channels

Channels describe ***discrete-time*** changes in systems that store quantum information. 

- Discrete-time change – change that occurs at separate, distinct time points (e.g., t = 0, 1, 2, …).
- Continuous process – change that occurs smoothly over time, at every instant (infinitesimally small time intervals).

This includes useful operatinons (such as **unitary operations** described by quantum gates and circuits) and chagnes we might wish to avoid (such as noise).

**Note**: we will be discussing channels as "abstract mathematical terms" in this lesson. *Not thinking about what is useful and what is not.*

Common names (big greek letters): $\Phi, \Psi, \Xi$ 

---

**AS A FUNCTION** (applied to density matrices)
- If a channel $\Phi$ is applied to a system, that is represtented by a density matrix $\rho$, then we obtain a system in the state $\Phi(\rho)$

## Requirements to become a channel

1. Channels are linear mappings.
2. Channels transform density matrices into density matrices.
    - **NOTE**: This includes the possibility that a channel is applied to **part of a compound system.**
  
Note: This coincides or analogous with the rule into the "simplified formulation of quantum information"

## Further details about channels
- Every channel $\Phi$ has an **input** system $X$ and an **output** system $Y$.
    - Conceptually speaking, $\Phi$ transforms $X$ to $Y$. Input and output are not considered to simultaneously co-exist. The input and output systems **DOES NOT NEED TO BE THE SAME** - they DO NOT NEED to have the same number of classical states.
    - The input and output *CAN BE* the same (i.e. $X=Y$), in which case we may simply view that $\Phi$ changes the state of this system. **This means that when $X=Y$, the channel is simply a state transformation on a single system, not a transfer between different systems.**

## Example of a channel

Suppose $Z$ is an additional system, $\Gamma$ is the classical state set of $Z$, and the pair $(Z,X)$ is in the state $\rho$. We can express $\rho$ in the following form.

$$ \rho = \sum_{a,b\in \Gamma} \ket{a}\bra{b}\otimes\rho_{a,b}$$

where $\rho_{a,b}$ is some matrix whose rows and columns correspond to whatever the classical state set of $X$ is (which is not given at this point)

Note: $\rho_{a,b}$ is not necessarily a density matrix on its own but the entire matrix $\rho$ is a density matrix.

In [2]:
import numpy as np

ketplus = np.array([[1/np.sqrt(3)], [1/np.sqrt(3)], [1/np.sqrt(3)]])
ketpsi = np.array([[np.sqrt(3)/2],[1/2]])

# say X is in the state 
X = ketplus.dot(ketplus.T)
print("X")
print(X)

# say Z is in the state
print()
Z = ketpsi.dot(ketpsi.T)
print("Z")
print(Z)

# the pair Z,X
Z_X = np.kron(Z,X)
print()
print("Z_X")
print(Z_X)

print()
gamma = [0, 1]
add = 0
gap = X.shape[0]
compose = np.zeros(Z_X.shape)
for a in gamma:
    for b in gamma:
        ket_a = np.array([[1] if a == i else [0] for i in range(2)])
        ket_b = np.array([[1] if b == i else [0] for i in range(2)])
        a_b = ket_a.dot(ket_b.T)
        p_a_b = Z_X[a*gap : a*gap+gap, b*gap : b*gap+gap]
        a_b_p_a_b = np.kron(a_b, p_a_b)
        print()
        print(a,b)
        print(a_b_p_a_b)
        compose += a_b_p_a_b

print()
print("composed matrix:")
print(compose)

X
[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]

Z
[[0.75      0.4330127]
 [0.4330127 0.25     ]]

Z_X
[[0.25       0.25       0.25       0.14433757 0.14433757 0.14433757]
 [0.25       0.25       0.25       0.14433757 0.14433757 0.14433757]
 [0.25       0.25       0.25       0.14433757 0.14433757 0.14433757]
 [0.14433757 0.14433757 0.14433757 0.08333333 0.08333333 0.08333333]
 [0.14433757 0.14433757 0.14433757 0.08333333 0.08333333 0.08333333]
 [0.14433757 0.14433757 0.14433757 0.08333333 0.08333333 0.08333333]]


0 0
[[0.25 0.25 0.25 0.   0.   0.  ]
 [0.25 0.25 0.25 0.   0.   0.  ]
 [0.25 0.25 0.25 0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.  ]]

0 1
[[0.         0.         0.         0.14433757 0.14433757 0.14433757]
 [0.         0.         0.         0.14433757 0.14433757 0.14433757]
 [0.         0.         0.         0.14433757 0.14433757 0.14433757]
 [

Applying the channel $\Phi$ to $X$ transforms it into $Y$, leaving $(Z,Y)$ in this state:
$$\sum_{a,b\in\Gamma} \ket{a}\bra{b}\otimes\Phi(\rho_{a,b}) $$

**Note: the channel is applied to a certain blocks only.**

Visually, If $\Gamma=\{0,\dots,m-1\}$ we can describe this transformation in terms of block matrices:

$$\rho=\left(\begin{matrix}
\rho_{0,0} & \dots & \rho_{0,m-1}\\
\vdots & \ddots & \vdots\\
\rho_{m-1,0} & \dots & \rho_{m-1,m-1}
\end{matrix}\right)\mapsto
\left(\begin{matrix}
\Phi(\rho_{0,0}) & \dots & \Phi(\rho_{0,m-1})\\
\vdots & \ddots & \vdots\\
\Phi(\rho_{m-1,0}) & \dots & \Phi(\rho_{m-1,m-1})
\end{matrix}\right)$$

The resulting density matrix (for every possible $Z$ and every density matrix $\rho$)

## Unitary channels
- unitary operations in simplified formulation but instead viewed as channels

Suppose $U$ is a unitary matrix representing a unitary operation on a system $X$.

**Note: In simplified formulation, we just denote this operation as matrix-vector multiplication.**

The channel $\Phi$ corresponding to this operation is defined as follows. 

$$\Phi(\rho)=UpU^\dagger $$

In mathematical terms, this is what we call **conjugation by the matrix U**.

- this is consistent that $\ket{\psi}\bra{\psi}$ being the density matrix representation of the quantum state vector $\ket{\psi}$.

- if $U$ is performed on $\ket{\psi}$, we obtain the quantum state vector $U\ket{\psi}$, whose density matrix representation is as follows:

$$ (U\ket{\psi})(U\ket{\psi})^\dagger = U\ket{\psi}\bra{\psi}U^\dagger$$

**In generality, we can express all density matrices as a convex combination of pure states.** That means this formulation works for all density matrices.

**FACT** 

This is always a valid channel. If the state of $(Z,X)$ is represented by a density matrix $\rho$ and $\Phi$ is applied to $X$, then we necessarily obtain a density matrix:

$$ (I_Z\otimes U)\space \rho\space (I_Z \otimes U)^\dagger $$

This means we can apply the unitary channel $\Phi$ to a part of a compound system.

### Example of unitary channel: Identity channel

The channel we obtain when we take $U=I$ is the identity channel:
$$ \text{Id}(\rho)=\rho $$

## Convex Combinations of Channels
- average together the channels

Let $\Phi_0$ and $\Phi_1$ be channels from $X$ to $Y$ and let $p\in[0,1]$.

- we assume both channels has same input $X$ and output $Y$

Consider applying $\Phi_0$ with probability $p$ and $\Phi_1$ with probability $1-p$. We can obtain a new channel:

$$ \Psi = p\Phi_0 + (1-p)\Phi_1 $$

- if we input $\rho$ in $\Psi$ we take the linear combination

$$ \Psi(\rho) = [p\Phi_0 + (1-p)\Phi_1]\space\rho = p\Phi_0(\rho) + (1-p)\Phi_1(\rho)$$

More generally, if $\Phi_0,\dots,\Phi_{m-1}$ are channels and $(p_0,\dots,p_{m-1})$ is a probability vector, then averaging in a similar way creates a new channel:

$$\Psi = \sum_{k=0}^{m-1} p_k\Phi_k$$

### Example of Convex Combinations of Channels: Mixed-Unitary Channels

Applying one of a collection of unitary operations to a systme yields a mixed unitary channel.

$$\Psi(\rho)=\sum_{k=0}^{m-1} p_k U_k\rho U_k^\dagger $$

Note: the set of unitary channels $U_k$ should have the same size.

**NOT EVERY CHANNEL IS A MIXED-UNITARY CHANNEL, we cannot get every channel this way. But, this is a common channel**

## Specific Examples of Channels

### Qubit reset

The *qubit reset channel* resets a qubit to the state $\ket{0}$ state.

$$ \Lambda(\rho) = \text{Tr}(\rho)\ket{0}\bra{0} $$

*Lambda symbol is pointing upward to the bloch sphere*

***NOTE: it is important to add the $\text{Tr}(\rho)$ in front, for the channel to become linear mapping.*** Keep in mind, sometimes, we need to think of channels if we apply it to a **non-density** matrix inputs. Because the smaller blocks of the entire density matrix is not a density matrix. 

### Example of Qubit Reset Applied to Compound System $\ket{\phi^+}$

Suppose $A$ and $B$ are qubits, $(A,B)$ is in the state $\ket{\phi^+}$, and $\Lambda$ is applied to $A$.

$$ \ket{\phi^+} = \frac{1}{\sqrt{2}}\ket{00}+\frac{1}{\sqrt{2}}\ket{11} $$

as a density matrix:

$$ \ket{\phi^+}\bra{\phi^+} = \left(\frac{1}{\sqrt{2}}\ket{00}+\frac{1}{\sqrt{2}}\ket{11}\right)\left(\frac{1}{\sqrt{2}}\bra{00}+\frac{1}{\sqrt{2}}\bra{11}\right)  $$

$$ \ket{\phi^+}\bra{\phi^+} = \frac{1}{2}\ket{00}\bra{00}+\frac{1}{2}\ket{00}\bra{11}+\frac{1}{2}\ket{11}\bra{00}+\frac{1}{2}\ket{11}\bra{11}$$

since,

$$ \ket{ab}\bra{cd} = (\ket{a}\otimes\ket{b})(\bra{c}\otimes\bra{d}) = \ket{a}\bra{c}\otimes\ket{b}\bra{d} $$

then, the formulation is equivalent to (from the lecture)

$$ \ket{\phi^+}\bra{\phi^+} = \frac{1}{2}\ket{0}\bra{0}\otimes\ket{0}\bra{0}+\frac{1}{2}\ket{0}\bra{1}\otimes\ket{0}\bra{1}+\frac{1}{2}\ket{1}\ket{0}\otimes\ket{1}\bra{0}+\frac{1}{2}\ket{1}\bra{1}\otimes\ket{1}\bra{1}$$

In [1]:
import numpy as np
# proof of this equality
a = 1
b = 0
c = 0
d = 1

ket_a = np.array([[1] if i == a else [0] for i in range(2)])
ket_b = np.array([[1] if i == b else [0] for i in range(2)])

ket_c = np.array([[1] if i == c else [0] for i in range(2)])
bra_c = ket_c.T
ket_d = np.array([[1] if i == d else [0] for i in range(2)])
bra_d = ket_d.T

# first formulation ket_a tensor ket_b X bra_c tensor bra_d
form1 = np.kron(ket_a, ket_b).dot(np.kron(bra_c, bra_d))
print("form 1 ketket X brabra")
print(form1)
print()

# second formulation ket_a X bra_c tensor ket_b X bra_d
form2 = np.kron(ket_a.dot(bra_c), ket_b.dot(bra_d))
print("form 2 ket X bra ket X bra")
print(form1)

form 1 ketket X brabra
[[0 0 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 0 0 0]]

form 2 ket X bra ket X bra
[[0 0 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 0 0 0]]


Then we can apply the channel to the first qubit, evaluate, and simplify:

$$ \frac{1}{2}\Lambda(\ket{0}\bra{0})\otimes\ket{0}\bra{0}+\frac{1}{2}\Lambda(\ket{0}\bra{1})\otimes\ket{0}\bra{1}+\frac{1}{2}\Lambda(\ket{1}\bra{0})\otimes\ket{1}\bra{0}+\frac{1}{2}\Lambda(\ket{1}\bra{1})\otimes\ket{1}\bra{1}$$

Note that $\text{Tr}(\ket{0}\bra{1}) = 0$ and $\text{Tr}(\ket{1}\bra{0}) = 0$, so we get

$$
\frac{1}{2}\ket{0}\bra{0}\otimes\ket{0}\bra{0}+
\frac{1}{2}\ket{0}\bra{0}\otimes\ket{1}\bra{1}=
\ket{0}\bra{0}\otimes\frac{I}{2}
$$

The first qubit is in state 0 while the second qubit is in the completely mixed state.

**NOTE: We did not get a $+$ state for system $B$**. You may think of this as collapsing the first qubit to 0 but remember it is a DIFFERENT BEHAVIOR since the second qubit is in completely mixed state and not $\ket{+}\bra{+}$.

### Complete Dephasing Channel

The *completely dephasing channel* zeros out off-diagonal matrix entries.


$$\Delta \begin{pmatrix} \alpha_{00} & \alpha_{01} \\ \alpha_{10} & \alpha_{11} \end{pmatrix} =\begin{pmatrix} \alpha_{00} & 0 \\ 0 & \alpha_{11}  \end{pmatrix}$$

*Delta corresponds to latin letter "D" which corresponds to "diagonal"*

Using Dirac notation,

$$ \Delta(\ket{0}\bra{0})=\ket{0}\bra{0} $$
$$ \Delta(\ket{1}\bra{0})=0 $$
$$ \Delta(\ket{0}\bra{1})=0 $$
$$ \Delta(\ket{1}\bra{1})=\ket{1}\bra{1} $$

The output is always $2\times 2$ matrix so in particular the output 0 means all 0 $2\times 2$ matrix.

### Example of Complete Dephasing Applied to Compound System $\ket{\phi^+}$

Suppose $A$ and $B$ are qubits, $(A,B)$ is in the state $\ket{\phi^+}$, and $\Delta$ is applied to $A$.

$$ \frac{1}{2}\Delta(\ket{0}\bra{0})\otimes\ket{0}\bra{0}+\frac{1}{2}\Delta(\ket{0}\bra{1})\otimes\ket{0}\bra{1}+\frac{1}{2}\Delta(\ket{1}\bra{0})\otimes\ket{1}\bra{0}+\frac{1}{2}\Delta(\ket{1}\bra{1})\otimes\ket{1}\bra{1}$$

$$=\frac{1}{2}\Delta(\ket{0}\bra{0})\otimes\ket{0}\bra{0}+\frac{1}{2}\Delta(\ket{1}\bra{1})\otimes\ket{1}\bra{1}$$

The result is **perfectly correlated pair of classical random bits**. By zeroing out the off-diagonal of a density matrix, we are *throwing away the quantum stuff* in a density matrix leaving a diagonal matrix that represents a classical probabilistic state.

Another way to think about this is that this channel represents a perfect noiseless classical channel that transmits a bit. 

So if we put a zero state or one state or a convex combination of those two states into the channel, that state comeout unchanged. 

If we put a quantum state into it, its as if the channel measures that state with a standard basis measurement and then transmit